{% set name = "segy" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/segy-{{ version }}.tar.gz
  sha256: 649f336c593492674db5a1b1e83cddef503f9e5201743d397fcc72d529bee9a8

build:
  entry_points:
    - segy = segy.cli.segy:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - fastentrypoints
    - pip
  run:
    - python >={{ python_min }},<3.13
    - fsspec >=2024.10.0
    - numpy >=2.0.0,<3.0.0
    - pydantic >=2.9.2,<3.0.0
    - pydantic-settings >=2.6.1,<3.0.0
    - numba >=0.59.1,<1.0.0
    - pandas >=2.2.2,<3.0.0
    - typer >=0.13.1,<0.14.0
    - rapidfuzz >=3.10.1,<4.0.0
    - eval-type-backport >=0.2.0,<0.3.0
  run_constrained:
    - gcsfs >=2024.10.0
    - s3fs >=2024.10.0
    - adlfs >=2024.7.0

test:
  imports:
    - segy
  commands:
    - pip check
    - segy --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/TGSAI/segy
  summary: The Ultimate Python SEG-Y I/O with Cloud Support and Schemas
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tasansal
