{% set name = "segy" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/segy-{{ version }}.tar.gz
  sha256: b14aceaccb01fb0382a6025c7b4b41bc4f4f756b954deeed5c2591346ac029e6

build:
  entry_points:
    - segy = segy.cli.segy:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >={{ python_min }},<3.14
    - uv-build >=0.8.17,<0.9.0
  run:
    - python >={{ python_min }},<3.14
    - fsspec >=2024.10.0
    - numpy >=2.0.0,<3.0.0
    - pydantic >=2.9.2,<3.0.0
    - pydantic-settings >=2.6.1,<3.0.0
    - numba >=0.61.0,<0.70.0
    - pandas >=2.2.2,<3.0.0
    - typer >=0.16.0,<0.17.0
    - rapidfuzz >=3.10.1,<4.0.0

test:
  imports:
    - segy
  commands:
    - pip check
    - segy --help
  requires:
    - python >={{ python_min }},<3.14
    - pip

about:
  home: https://github.com/TGSAI/segy
  summary: The Ultimate Python SEG-Y I/O with Cloud Support and Schemas
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tasansal
