{% set name = "segy" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segy-{{ version }}.tar.gz
  sha256: 7393d4db24ee5065a02807e68e3d341d4d4c37d99a85f0323bf1670b9d366a97

build:
  entry_points:
    - segy = segy.cli.segy:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core
    - fastentrypoints
    - pip
  run:
    - python >=3.9,<3.13
    - fsspec >=2024.2.0
    - numpy >=1.26.4,<2.0.0
    - pydantic >=2.6.4,<3.0.0
    - pydantic-settings >=2.2.1,<3.0.0
    - numba >=0.59.0,<0.60.0
    - pandas >=2.2.1,<3.0.0
    - typer >=0.10.0,<0.10.0
    - eval-type-backport >=0.1.3,<0.2.0
    - click-params >=0.5.0,<0.6.0
  run_constrained:
    - gcsfs >=2024.2.0
    - s3fs >=2024.2.0
    - adlfs >=2024.2.0

test:
  imports:
    - segy
  commands:
    - pip check
    - segy --help
  requires:
    - pip

about:
  home: https://github.com/TGSAI/segy
  summary: The Ultimate Python SEG-Y I/O with Cloud Support and Schemas
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tasansal
