{% set name = "segy" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segy-{{ version }}.tar.gz
  sha256: 271fa61c7b50978cc055d9d945a211e644d4185d212cfe62274822af654cc485

build:
  entry_points:
    - segy = segy.cli.segy:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core
    - fastentrypoints
    - pip
  run:
    - python >=3.9,<3.13
    - fsspec >=2024.9.0
    - numpy >=1.26.4,<2.0.0
    - pydantic >=2.9.0,<3.0.0
    - pydantic-settings >=2.4.0,<3.0.0
    - numba >=0.60.0,<1.0.0
    - pandas >=2.2.2,<3.0.0
    - bidict >=0.23.1,<0.24.0
    - typer >=0.12.5,<0.13.0
    - rapidfuzz >=3.9.7,<4.0.0
    - eval-type-backport >=0.2.0,<0.3.0
  run_constrained:
    - gcsfs >=2024.9.0
    - s3fs >=2024.9.0
    - adlfs >=2024.7.0

test:
  imports:
    - segy
  commands:
    - pip check
    - segy --help
  requires:
    - pip

about:
  home: https://github.com/TGSAI/segy
  summary: The Ultimate Python SEG-Y I/O with Cloud Support and Schemas
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tasansal
