{% set name = "segy" %}
{% set version = "0.4.1.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/segy-{{ version }}.tar.gz
  sha256: e45ab7d6008bd75e490638143329992a61af57916e064086ce559e77e62500e3

build:
  entry_points:
    - segy = segy.cli.segy:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >={{ python_min }},<3.13
    - setuptools
    - wheel
    - fastentrypoints
    - pip
  run:
    - python >=3.10,<3.14
    - fsspec >=2024.10.0
    - numpy >=2.0.0,<3.0.0
    - pydantic >=2.9.2,<3.0.0
    - pydantic-settings >=2.6.1,<3.0.0
    - numba >=0.61.0,<0.70.0
    - pandas >=2.2.2,<3.0.0
    - typer >=0.13.1,<0.14.0
    - rapidfuzz >=3.10.1,<4.0.0

test:
  imports:
    - segy
  commands:
    - pip check
    - segy --help
  requires:
    - pip

about:
  home: https://github.com/TGSAI/segy
  summary: The Ultimate Python SEG-Y I/O with Cloud Support and Schemas
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tasansal
